import { QUESTION_TYPES } from "./questionTypes";

export const questions = [
  {
    id: "elementary-1",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Скільки буде 48 ÷ 6 + 7?",
    answers: ["13", "15", "8", "17"],
    correctIndex: 1,
    pointValue: 1,
    explanation: "Спочатку виконуємо ділення: 48 ÷ 6 = 8. Потім додаємо 7 й отримуємо 15.",
  },
  {
    id: "elementary-2",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Яке число становить 25% від 80?",
    answers: ["15", "20", "25", "40"],
    correctIndex: 1,
    pointValue: 1,
    explanation: "25% — це одна четверта. 80 ÷ 4 = 20.",
  },
  {
    id: "elementary-3",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Обчисли: 3² + 4².",
    answers: ["12", "24", "25", "49"],
    correctIndex: 2,
    pointValue: 1,
    explanation: "3² = 9, а 4² = 16. Сума 9 + 16 дорівнює 25.",
  },
  {
    id: "elementary-4",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Який дріб дорівнює 0,75?",
    answers: ["1/2", "2/3", "3/4", "4/5"],
    correctIndex: 2,
    pointValue: 1,
    explanation: "0,75 = 75/100. Скорочуємо чисельник і знаменник на 25 та отримуємо 3/4.",
  },
  {
    id: "elementary-5",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Розв’яжи рівняння: 5x = 35.",
    answers: ["x = 5", "x = 6", "x = 7", "x = 8"],
    correctIndex: 2,
    pointValue: 1,
    explanation: "Ділимо обидві частини рівняння на 5: x = 35 ÷ 5 = 7.",
  },
  {
    id: "elementary-6",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Периметр квадрата дорівнює 36 см. Яка довжина його сторони?",
    answers: ["6 см", "8 см", "9 см", "12 см"],
    correctIndex: 2,
    pointValue: 1,
    explanation: "У квадрата чотири рівні сторони. 36 ÷ 4 = 9 см.",
  },
  {
    id: "elementary-7",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Яке число наступне у послідовності: 2, 5, 8, 11, …?",
    answers: ["12", "13", "14", "15"],
    correctIndex: 2,
    pointValue: 1,
    explanation: "Кожне наступне число збільшується на 3, тому 11 + 3 = 14.",
  },
  {
    id: "elementary-8",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Автомобіль проїхав 180 км за 3 години. Якою була середня швидкість?",
    answers: ["45 км/год", "60 км/год", "90 км/год", "120 км/год"],
    correctIndex: 1,
    pointValue: 1,
    explanation: "Швидкість дорівнює відстані, поділеній на час: 180 ÷ 3 = 60 км/год.",
  },
  {
    id: "elementary-9",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Спрости вираз: 4a + 3a − 2a.",
    answers: ["5a", "6a", "7a", "9a"],
    correctIndex: 0,
    pointValue: 1,
    explanation: "Додаємо коефіцієнти подібних доданків: 4 + 3 − 2 = 5, отже маємо 5a.",
  },
  {
    id: "elementary-10",
    type: QUESTION_TYPES.SINGLE_CHOICE,
    text: "Яка площа прямокутника зі сторонами 7 см і 5 см?",
    answers: ["12 см²", "24 см²", "30 см²", "35 см²"],
    correctIndex: 3,
    pointValue: 1,
    explanation: "Площа прямокутника — це добуток його сторін: 7 × 5 = 35 см².",
  },
];
